# Generated by Django 4.0.3 on 2022-04-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='text_notice',
            field=models.CharField(default='text', max_length=3000),
        ),
        migrations.AddField(
            model_name='lecture',
            name='text_recommendation',
            field=models.CharField(default='text', max_length=3000),
        ),
        migrations.AddField(
            model_name='lecture',
            name='text_summary',
            field=models.CharField(default='text', max_length=3000),
        ),
    ]
